{
 "title": "OpenTelemetry semantic conventions",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "faas-metrics",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "faas.invoke_duration",
     "type": "timeseries",
     "description": "Measures the duration of the function's logic execution",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(faas_invoke_duration_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.init_duration",
     "type": "timeseries",
     "description": "Measures the duration of the function's initialization, such as a cold start",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(faas_init_duration_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.coldstarts",
     "type": "timeseries",
     "description": "Number of invocation cold starts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{coldstart}" } },
     "targets": [
      { "expr": "avg(faas_coldstarts)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.errors",
     "type": "timeseries",
     "description": "Number of invocation errors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{error}" } },
     "targets": [
      { "expr": "avg(faas_errors)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.invocations",
     "type": "timeseries",
     "description": "Number of successful invocations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{invocation}" } },
     "targets": [
      { "expr": "avg(faas_invocations)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.timeouts",
     "type": "timeseries",
     "description": "Number of invocation timeouts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{timeout}" } },
     "targets": [
      { "expr": "avg(faas_timeouts)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.mem_usage",
     "type": "timeseries",
     "description": "Distribution of max memory usage per invocation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(faas_mem_usage_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.cpu_usage",
     "type": "timeseries",
     "description": "Distribution of CPU usage per invocation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(faas_cpu_usage_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "faas.net_io",
     "type": "timeseries",
     "description": "Distribution of net I/O usage per invocation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(faas_net_io_sum)", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "system-metrics",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "system.cpu.time",
     "type": "timeseries",
     "description": "Seconds each logical CPU spent on each mode",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(system_cpu_time)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.cpu.utilization",
     "type": "timeseries",
     "description": "Difference in system.cpu.time since the last measurement, divided by the elapsed time and number of logical CPUs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      { "expr": "avg(system_cpu_utilization)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.cpu.frequency",
     "type": "timeseries",
     "description": "Reports the current frequency of the CPU in Hz",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{Hz}" } },
     "targets": [
      { "expr": "avg(system_cpu_frequency)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.cpu.physical.count",
     "type": "timeseries",
     "description": "Reports the number of actual physical processor cores on the hardware",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{cpu}" } },
     "targets": [
      { "expr": "avg(system_cpu_physical_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.cpu.logical.count",
     "type": "timeseries",
     "description": "Reports the number of logical (virtual) processor cores created by the operating system to manage multitasking",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{cpu}" } },
     "targets": [
      { "expr": "avg(system_cpu_logical_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.memory.usage",
     "type": "timeseries",
     "description": "Reports memory in use by state.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_memory_usage)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.memory.limit",
     "type": "timeseries",
     "description": "Total memory available in the system.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_memory_limit)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.memory.utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      { "expr": "avg(system_memory_utilization)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.paging.usage",
     "type": "timeseries",
     "description": "Unix swap or windows pagefile usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_paging_usage)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.paging.utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      { "expr": "avg(system_paging_utilization)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.paging.faults",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{fault}" } },
     "targets": [
      { "expr": "avg(system_paging_faults)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.paging.operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{operation}" } },
     "targets": [
      { "expr": "avg(system_paging_operations)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.disk.io",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_disk_io)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.disk.operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{operation}" } },
     "targets": [
      { "expr": "avg(system_disk_operations)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.disk.io_time",
     "type": "timeseries",
     "description": "Time disk spent activated",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(system_disk_io_time)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.disk.operation_time",
     "type": "timeseries",
     "description": "Sum of the time each operation took to complete",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(system_disk_operation_time)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "system.disk.merged",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{operation}" } },
     "targets": [
      { "expr": "avg(system_disk_merged)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.filesystem.usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_filesystem_usage)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.filesystem.utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      {
       "expr": "avg(system_filesystem_utilization)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "system.network.dropped",
     "type": "timeseries",
     "description": "Count of packets that are dropped or discarded even though there was no error",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{packet}" } },
     "targets": [
      { "expr": "avg(system_network_dropped)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.network.packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{packet}" } },
     "targets": [
      { "expr": "avg(system_network_packets)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.network.errors",
     "type": "timeseries",
     "description": "Count of network errors detected",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{error}" } },
     "targets": [
      { "expr": "avg(system_network_errors)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.network.io",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(system_network_io)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.network.connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{connection}" } },
     "targets": [
      {
       "expr": "avg(system_network_connections)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "system.processes.count",
     "type": "timeseries",
     "description": "Total number of processes in each state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{process}" } },
     "targets": [
      { "expr": "avg(system_processes_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.processes.created",
     "type": "timeseries",
     "description": "Total number of processes created over uptime of the host",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{process}" } },
     "targets": [
      { "expr": "avg(system_processes_created)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system.linux.memory.available",
     "type": "timeseries",
     "description": "An estimate of how much memory is available for starting new applications, without causing swapping",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(system_linux_memory_available)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "database-metrics",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "db.client.connections.usage",
     "type": "timeseries",
     "description": "The number of connections that are currently in state described by the `state` attribute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{connection}" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_usage)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.idle.max",
     "type": "timeseries",
     "description": "The maximum number of idle open connections allowed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{connection}" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_idle_max)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.idle.min",
     "type": "timeseries",
     "description": "The minimum number of idle open connections allowed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{connection}" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_idle_min)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.max",
     "type": "timeseries",
     "description": "The maximum number of open connections allowed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{connection}" } },
     "targets": [
      { "expr": "avg(db_client_connections_max)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "db.client.connections.pending_requests",
     "type": "timeseries",
     "description": "The number of pending requests for an open connection, cumulative for the entire pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{request}" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_pending_requests)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.timeouts",
     "type": "timeseries",
     "description": "The number of connection timeouts that have occurred trying to obtain a connection from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{timeout}" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_timeouts)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.create_time",
     "type": "timeseries",
     "description": "The time it took to create a new connection",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_create_time_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.wait_time",
     "type": "timeseries",
     "description": "The time it took to obtain an open connection from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_wait_time_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "db.client.connections.use_time",
     "type": "timeseries",
     "description": "The time between borrowing a connection and returning it to the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_use_time_sum)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "jvm-metrics",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "jvm.memory.used",
     "type": "timeseries",
     "description": "Measure of memory used.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_memory_used)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.memory.committed",
     "type": "timeseries",
     "description": "Measure of memory committed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_memory_committed)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.memory.limit",
     "type": "timeseries",
     "description": "Measure of max obtainable memory.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_memory_limit)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.memory.used_after_last_gc",
     "type": "timeseries",
     "description": "Measure of memory used, as measured after the most recent garbage collection event on this pool.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_after_last_gc)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "jvm.gc.duration",
     "type": "timeseries",
     "description": "Duration of JVM garbage collection actions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(jvm_gc_duration_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.thread.count",
     "type": "timeseries",
     "description": "Number of executing platform threads.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{thread}" } },
     "targets": [
      { "expr": "avg(jvm_thread_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.class.loaded",
     "type": "timeseries",
     "description": "Number of classes loaded since JVM start.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{class}" } },
     "targets": [
      { "expr": "avg(jvm_class_loaded)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.class.unloaded",
     "type": "timeseries",
     "description": "Number of classes unloaded since JVM start.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{class}" } },
     "targets": [
      { "expr": "avg(jvm_class_unloaded)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.class.count",
     "type": "timeseries",
     "description": "Number of classes currently loaded.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{class}" } },
     "targets": [
      { "expr": "avg(jvm_class_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.cpu.count",
     "type": "timeseries",
     "description": "Number of processors available to the Java virtual machine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{cpu}" } },
     "targets": [
      { "expr": "avg(jvm_cpu_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.cpu.time",
     "type": "timeseries",
     "description": "CPU time used by the process as reported by the JVM.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "avg(jvm_cpu_time)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.cpu.recent_utilization",
     "type": "timeseries",
     "description": "Recent CPU utilization for the process as reported by the JVM.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      {
       "expr": "avg(jvm_cpu_recent_utilization)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "jvm-metrics-experimental",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "jvm.memory.init",
     "type": "timeseries",
     "description": "Measure of initial memory requested.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_memory_init)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.system.cpu.utilization",
     "type": "timeseries",
     "description": "Recent CPU utilization for the whole system as reported by the JVM.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "1" } },
     "targets": [
      {
       "expr": "avg(jvm_system_cpu_utilization)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "jvm.system.cpu.load_1m",
     "type": "timeseries",
     "description": "Average CPU load of the whole system for the last minute as reported by the JVM.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{run_queue_item}" } },
     "targets": [
      { "expr": "avg(jvm_system_cpu_load_1m)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.buffer.memory.usage",
     "type": "timeseries",
     "description": "Measure of memory used by buffers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_buffer_memory_usage)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.buffer.memory.limit",
     "type": "timeseries",
     "description": "Measure of total memory capacity of buffers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "avg(jvm_buffer_memory_limit)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm.buffer.count",
     "type": "timeseries",
     "description": "Number of buffers in the pool.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{buffer}" } },
     "targets": [
      { "expr": "avg(jvm_buffer_count)", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "messaging",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "messaging.publish.duration",
     "type": "timeseries",
     "description": "Measures the duration of publish operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(messaging_publish_duration_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "messaging.receive.duration",
     "type": "timeseries",
     "description": "Measures the duration of receive operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(messaging_receive_duration_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "messaging.deliver.duration",
     "type": "timeseries",
     "description": "Measures the duration of deliver operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(messaging_deliver_duration_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "messaging.publish.messages",
     "type": "timeseries",
     "description": "Measures the number of published messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{message}" } },
     "targets": [
      {
       "expr": "avg(messaging_publish_messages)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "messaging.receive.messages",
     "type": "timeseries",
     "description": "Measures the number of received messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{message}" } },
     "targets": [
      {
       "expr": "avg(messaging_receive_messages)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "messaging.deliver.messages",
     "type": "timeseries",
     "description": "Measures the number of delivered messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{message}" } },
     "targets": [
      {
       "expr": "avg(messaging_deliver_messages)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "http",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "http.server.request.duration",
     "type": "timeseries",
     "description": "Duration of HTTP server requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_server_request_duration_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.server.active_requests",
     "type": "timeseries",
     "description": "Number of active HTTP server requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{request}" } },
     "targets": [
      {
       "expr": "avg(http_server_active_requests)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.server.request.body.size",
     "type": "timeseries",
     "description": "Size of HTTP server request bodies.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(http_server_request_body_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.server.response.body.size",
     "type": "timeseries",
     "description": "Size of HTTP server response bodies.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(http_server_response_body_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.client.request.duration",
     "type": "timeseries",
     "description": "Duration of HTTP client requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_client_request_duration_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.client.request.body.size",
     "type": "timeseries",
     "description": "Size of HTTP client request bodies.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(http_client_request_body_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http.client.response.body.size",
     "type": "timeseries",
     "description": "Size of HTTP client response bodies.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(http_client_response_body_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "rpc-metrics",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "rpc.server.duration",
     "type": "timeseries",
     "description": "Measures the duration of inbound RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "avg(rpc_server_duration_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "rpc.server.request.size",
     "type": "timeseries",
     "description": "Measures the size of RPC request messages (uncompressed).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_server_request_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.server.response.size",
     "type": "timeseries",
     "description": "Measures the size of RPC response messages (uncompressed).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_server_response_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.server.requests_per_rpc",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{count}" } },
     "targets": [
      {
       "expr": "avg(rpc_server_requests_per_rpc_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.server.responses_per_rpc",
     "type": "timeseries",
     "description": "Measures the number of messages sent per RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{count}" } },
     "targets": [
      {
       "expr": "avg(rpc_server_responses_per_rpc_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.client.duration",
     "type": "timeseries",
     "description": "Measures the duration of outbound RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "avg(rpc_client_duration_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "rpc.client.request.size",
     "type": "timeseries",
     "description": "Measures the size of RPC request messages (uncompressed).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_client_request_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.client.response.size",
     "type": "timeseries",
     "description": "Measures the size of RPC response messages (uncompressed).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_client_response_size_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.client.requests_per_rpc",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "{count}" } },
     "targets": [
      {
       "expr": "avg(rpc_client_requests_per_rpc_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc.client.responses_per_rpc",
     "type": "timeseries",
     "description": "Measures the number of messages sent per RPC.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "{count}" } },
     "targets": [
      {
       "expr": "avg(rpc_client_responses_per_rpc_sum)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}